name: Build Status

on:
  push:
    branches:
      - trunk
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-plugin:
    name: Create an installable plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2.36.0
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr

      - name: Install NodeJS
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24
          cache: npm

      - name: Log debug information
        run: |
          echo "::group::PHP version"
          php --version
          echo "::endgroup::"
          echo "::group::Composer version"
          composer --version
          echo "::endgroup::"
          echo "::group::Node version"
          node --version
          echo "::endgroup::"
          echo "::group::NPM Version"
          npm --version
          echo "::endgroup::"

      - name: Install Composer dependencies
        run:
          composer install --no-progress --no-ansi --no-interaction --no-dev

      - name: Install Node dependencies
        run: npm install

      - name: Build plugin
        run: npm run build
