name: PHP Compatibility

on:
  push:
    branches:
      - trunk
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  php-comatibility:
    name: Check PHP compatibility
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2.36.0
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr

      - name: Install Composer dependencies
        run:
          composer install --no-progress --no-ansi --no-interaction

      - name: Make Composer packages available globally
        run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH

      - name: Run PHP compatibility tests
        run: composer run automation:lint:compat | cs2pr
